### ISSUE TITLE
Room details

### ISSUE THREAD

**Issue by nadonomy** [vector-im/compound#116]
_Developing..._

Contains:

```[tasklist]
# Sub components
- [ ] https://github.com/vector-im/compound/issues/117
- [ ] Room title
- [ ] Room address
- [ ] Badge
- [ ] Topic
- [ ] List
    - [ ] List Button
```

**Comment by germain-gg** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/25883

This will not be a compound component as it exists only in one downstream project. However it uses a composition of Compound components to display itself

**Comment by germain-gg** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/25883

This will not be a compound component as it exists only in one downstream project. However it uses a composition of Compound components to display itself
