### ISSUE TITLE
css-loader reports "autoprefixer: start value has mixed support, consider using flex-start instead"

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/compound#134]
Which feels like we should either be ignoring an error, or fixing it.

**Comment by dav-is** [comment]
I was looking into this briefly and it looks like these are what's causing it:
https://github.com/vector-im/compound-web/blob/39aff6e8410cffca7667ff8515604f044310bd4c/src/components/Alert/Alert.module.css#L21-L22

**Comment by germain-gg** [comment]
I don't think it should be Compound's responsibility to cater for downstream's projects compatibility.
This project advertises its browser support via `browserslist` and `start/end` are valid under those rules. 

See my review of this PR for an elaborated answer, https://github.com/vector-im/compound-web/pull/111

**Comment by weeman1337** [comment]
Thanks Germain. I will try to solve this in the downstream project.
