### ISSUE TITLE
AvatarStack doesn't allow non-avatar elements in the stack

### ISSUE THREAD

**Issue by t3chguy** [vector-im/compound#215]
Element Web's FacePile looks like this:

![image](https://github.com/vector-im/compound/assets/2403652/e7b38625-eb6e-4578-8a4a-5bccc34c79fb)

It has an extra overflow tile "..." at the end which follows the stacking behaviour. Due to the styling of compound-web the style is not applied and it ends up not being stacked. 

![image](https://github.com/vector-im/compound/assets/2403652/97788d31-c890-4e1e-bff2-4c9d1e24bd99)

![image](https://github.com/vector-im/compound/assets/2403652/1dd2406c-7005-4e23-a9f6-3d7e8716ebd6)

Either relax the selector or export the class/wrapper element to allow stacking things other than Compound avatars to enable wider reuse. Otherwise code ends up having to work around it and duplicate logic which can de-sync:

![image](https://github.com/vector-im/compound/assets/2403652/77a66550-6263-49e7-b9b4-b25214911a4a)

Partly caused https://github.com/vector-im/element-web/issues/26112

**Comment by Johennes** [comment]
Once this is done, we should also clean up the temporary workaround made in https://github.com/matrix-org/matrix-react-sdk/pull/11527.

**Comment by t3chguy** [comment]
This was fixed by @germain-gg
