### ISSUE TITLE
Button component does not forward refs in compound-web

### ISSUE THREAD

**Issue by sandhose** [vector-im/compound#219]
The [<Button> component](https://vector-im.github.io/compound-web/?path=/story/button--primary) in compound-web is not forwarding the ref to the underlying component.
This is an issue because when I tried to use Radix's Alert dialog, it could not autofocus on the button, because it was missing the ref.

I did not do it back in this PR (https://github.com/vector-im/compound-web/pull/47) because it was hard to properly type, because of the generic `as` prop.

cc @germain-gg

**Comment by kerryarchibald** [comment]
Closed by https://github.com/vector-im/compound-web/commit/e7f673d885282555e47380943f7162746058dc07
