### ISSUE TITLE
Auto transform :hover for better mobile support

### ISSUE THREAD

**Issue by germain-gg** [vector-im/compound#220]
Following up on https://github.com/vector-im/compound-web/pull/80

We should try to automate this. 
Here's a list of things we need to look into and try to apply to the project

1. Try to apply a PostCSS transformation
2. Add a linter rule to flag that we can not use `:hover` directly
3. If all else failed, create a style guide document

**Comment by robintown** [comment]
I managed to find a stylelint plugin that will do what we want: https://www.npmjs.com/package/stylelint-plugin-defensive-css#accidental-hover However there's one bug in it that ideally should be fixed first, to avoid having to rewrite a bunch of media features across compound-web: https://github.com/yuschick/stylelint-plugin-defensive-css/pull/17 Let's wait for that to be merged.
