### ISSUE TITLE
Add read-only states for input controls

### ISSUE THREAD

**Issue by janogarcia** [vector-im/compound#251]
Suggested by @sandhose.

Specs available on Figma:

- [ ] [Checkbox](https://www.figma.com/file/rTaQE2nIUSLav4Tg3nozq7/Compound-Web-Components?type=design&node-id=119-153&mode=design&t=VJZXWJe8jYU2ZyYK-0)
- [ ] [Radio](https://www.figma.com/file/rTaQE2nIUSLav4Tg3nozq7/Compound-Web-Components?type=design&node-id=129-4462&mode=design&t=VJZXWJe8jYU2ZyYK-0)
- [ ] [Toggle](https://www.figma.com/file/rTaQE2nIUSLav4Tg3nozq7/Compound-Web-Components?type=design&node-id=129-4463&mode=design&t=VJZXWJe8jYU2ZyYK-0)

**Comment by sandhose** [comment]
Implemented in vector-im/compound-web#108
Check it out here: https://quenting-forms-cleanup.compound-web.pages.dev/?path=/story/form-kitchen-sink--read-only

**Comment by kerryarchibald** [comment]
Closed by https://github.com/vector-im/compound-web/pull/108
