### ISSUE TITLE
C4.3: Compound Packages → iOS

### ISSUE THREAD

**Issue by nadonomy** [vector-im/compound#27]
Child issue in the compound-ios repo: https://github.com/orgs/vector-im/projects/52/views/16?pane=issue&itemId=18190552

**Comment by gsouquet** [comment]
The integration is working, https://matrix.to/#/!YJUhVuekhcNbIWyeId:matrix.org/$50u7OG3DMWzTP5jXkhsclrsr734UNY2l0n9dZSLtlQo?via=matrix.org&via=element.io&via=one.ems.host
