### ISSUE TITLE
Solid chat icon

### ISSUE THREAD

**Issue by kerryarchibald** [vector-im/compound#274]
Figma: https://www.figma.com/file/gkNXqPoiJhEv2wt0EJpew4/Compound-Icons?type=design&node-id=1098-28211&mode=design&t=UfapfbEDa7Muwp3T-0

Video rooms need to link the chat/timeline from the room header. Other room header icons are all solid.

EW issue: https://github.com/vector-im/element-web/issues/26181

EW fix: (using custom css to make existing chat icon solid)
![image](https://github.com/vector-im/compound/assets/3055605/c253ade2-64ab-4307-a184-a07d3689c25e)

https://www.figma.com/file/gkNXqPoiJhEv2wt0EJpew4/Compound-Icons?type=design&node-id=3092-21&mode=design&t=FeubIJWLyiD3mcLi-0

**Comment by americanrefugee** [comment]
I created a [new icon](https://www.figma.com/file/gkNXqPoiJhEv2wt0EJpew4/Compound-Icons?type=design&node-id=3092-21&mode=design&t=gKCu5ufSj9dnu83x-4) and [room header component](https://www.figma.com/file/rTaQE2nIUSLav4Tg3nozq7/Compound-Web-Components?type=design&node-id=2996-17490&mode=design&t=wkBXeDJWuNL511WL-4) for video rooms to show a solid chat icon button. Do you  need anything else?
