### ISSUE TITLE
Correct tooltip delay

### ISSUE THREAD

**Issue by kerryarchibald** [vector-im/compound#280]
# Platform

- Web

# Package version

- ...

# Description

Tooltips have a 300ms delay. Some (or all?) tooltips should open without delay. Eg https://github.com/vector-im/element-web/issues/26570#issuecomment-1809944191

**Comment by americanrefugee** [comment]
For any non-labeled buttons, the tooltip should show on hover after a 300ms delay.

For icons in the room header and disabled buttons, the tooltip should show instantly.

**Comment by americanrefugee** [comment]
After further considering other use cases besides room header and details, here are more general rules-of-thumb:

### **DESKTOP**

**For non-labelled, interactive elements that do something:** Show a tooltip on hover after a 300ms delay
Example: Any Icon-only buttons that performs some action

**For non-labelled, interactive elements that do nothing:** Show a tooltip on hover instantly
Examples: 
- Room decoration (public, encryption, trusted, not trusted, etc.)
- Status indicators
- Disabled buttons of any kind

**Exceptions:** Depends on the use case
Examples:
- Facepile in a timeline on the right
   - On hover there is valuable information with a changing value ("Seen by X people"), therefore show the tooltip immediately
- Room description on room detail view
   - By default the room description is collapsed into an interactive component (essentially a big button). The summary itself is not technically a label, but the hover state on rollover indicates that the element is interactive. There's no need to show any further tooltip at all.
   - Other examples we shall discover along the way :)

### **MOBILE**

- IF possible, show a tooltip after long-pressing any non-labelled, interactive element

---
Lemme know if you disagree with anything above

**Comment by robintown** [comment]
Related issue: https://github.com/vector-im/compound/issues/234
