### ISSUE TITLE
C4.4: Compound Packages → OIDC

### ISSUE THREAD

**Issue by nadonomy** [vector-im/compound#30]

**Comment by gsouquet** [comment]
The OIDC team is using Tailwind / HTML templates and a React app.

https://github.com/matrix-org/matrix-authentication-service
- `templates/`
- [Tailwind config](https://github.com/matrix-org/matrix-authentication-service/blob/main/frontend/tailwind.config.cjs) (useful for token overrides)
- `frontend/` (the React app)

They have a Storybook setup http://matrix-org.github.io/matrix-authentication-service/storybook/

Looping @sandhose in as one of the OIDC contributor

**Comment by gsouquet** [comment]
A first integration was made with @sandhose , see https://github.com/matrix-org/matrix-authentication-service/pull/1159
