### ISSUE TITLE
C5: Document visuals: Colour and theming

### ISSUE THREAD

**Issue by nadonomy** [vector-im/compound#41]
Includes:

- Audit
- Research
- Values
- Taxonomy
- Guidelines
- Figma

Status for each item tracked in related board.

TODO: Add link.

**Comment by gsouquet** [comment]
Done, the generated styles have been documented in figma here, https://www.figma.com/file/PpKepmHKGikp33Ql7iivbn/Compound-Styles?type=design&node-id=37-3&t=HnfOCBgvFhdBPTSJ-0
