### ISSUE TITLE
Avatar component tokens

### ISSUE THREAD

**Issue by gsouquet** [vector-im/compound#73]
We need to define the values in the colour scale we want to use for the avatar component

As currently defined in https://github.com/vector-im/compound-web/blob/main/src/components/Avatar/Avatar.module.css

**Comment by janogarcia** [comment]
Mapping to solid colors like this will lead to quite dark, high-contrast colors with considerable visual weight:

```
#368bd6 → blue.900
#ac3ba8 → fuchsia.900
#03b381 → green.900
#e64f7a → pink.900
#ff812d → orange.900
#2dc2c5 → cyan.900
#5c56f5 → purple.900
#74d12c → lime.900
```

I'd say, let's remap them like this until we get to consider what to do about user colors in general in Element X:

![Non Boring Gradients (Community) – Figma](https://user-images.githubusercontent.com/60790/227527748-1c06d63e-d5fe-4688-8418-2447b2abb73b.png)

So, for `#368bd6` you would have:

- Background: `blue.300`
- Border: `blue.400`
- Text: `blue.900`

You'd follow an equivalent mapping for the other hues above. So, for `#ac3ba8`:

- Background: `fuchsia.300`
- Border: `fuchsia.400`
- Text: `fuchsia.900`

And so on.
